name: .NET CI

on:
  workflow_dispatch:
jobs:
  windowspublish:
    runs-on: windows-latest
    name: Windows Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'

      - name: Windows Publish
        env:
          runtime: win-x64
        run: |
          $options=@("--configuration", "Release", "-p:PublishSingleFile=true", "-p:DebugType=embedded", "--no-self-contained", "-p:SourceRevisionId=$(git rev-parse --short HEAD)")
          dotnet publish OpenTabletDriver.Daemon $options --runtime $ENV:runtime -o build/$ENV:runtime
          dotnet publish OpenTabletDriver.Console $options --runtime $ENV:runtime -o build/$ENV:runtime
          dotnet publish OpenTabletDriver.UX.Wpf $options --runtime $ENV:runtime -o build/$ENV:runtime

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenTabletDriver win-x64
          path: build/win-x64
          if-no-files-found: error
          compression-level: 9

  linter:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'

      - name: Lint Changed Files
        run: |
          mapfile -t files < <(git diff --name-only --diff-filter=AM HEAD^ HEAD | grep '.*\.cs$')
          if [ ${#files[@]} -ne 0 ]; then dotnet format OpenTabletDriver.sln --verify-no-changes --include "${files[@]}"; fi

  unittests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@4
        with:
          dotnet-version: '8'

      - name: Run tests
        run: dotnet test

  slnf:
    name: Validate Solution Filters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@4
        with:
          dotnet-version: '8'

      - name: Windows
        run: dotnet restore OpenTabletDriver.Windows.slnf
